version: '3.7'
services:
  nethermind:
    container_name: nethermind
    image: nethermind/nethermind:1.21.0
    restart: always
    command: --config inertiachain
    stop_grace_period: 1m
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - ./genesis:/config/genesis
      - ./inertiachain.cfg:/nethermind/configs/inertiachain.cfg
      - ./static-nodes.json:/nethermind/Data/static-nodes.json
      - ./nethermind_db:/nethermind/nethermind_db
      - ./keystore:/nethermind/keystore
    environment:
      NETHERMIND_CONFIG : inertiachain
    logging:
      driver: "local"
 